const CATEGORIES = [
  "All",
  "Desktops",
  "Laptops",
  "Epson Printers",
  "HP Printers",
  "Plotting Machines",
  "Heat Press Machines",
  "Laminators",
  "CCTV'S",
  "Networking",
  "Cables",
  "Laptop Adapters",
  "Storage",
  "UPS",
  "Epson Inks",
  "Toners",
  "Kyocera/Hp Toner Powders",
  "Routers",
  "RAMS",
  "Professional Cameras",
  "Computer Repair & Maintenance",
];

const PRODUCTS = [
  {
    id: "lap-001",
    name: "HP EliteDesk 800 G5 Desktop",
    category: "Desktops",
    icon: "🖥️",
    image: "assets/products/hp compaq pro.jpg",
    price: 18000,
    specs: ["Intel Core i3-8th Gen", "16GB DDR4 RAM", "256GB SSD", "Windows 11 Pro"],
  },
  {
    id: "dsk-002",
    name: "HP MINI ELITEDESK 800 G5",
    category: "Desktops",
    icon: "🖥️",
    price: 22000,
    specs: ["Intel Core i5-9TH GEN", "8GB DDR5 RAM", "256 SSD", "Intel UHD Graphics"],
  },
  {
    id: "dsk-003",
    name: "HP PRODESK 405 G6 AMD RYZEN",
    category: "Desktops",
    icon: "🎮",
    price: 25000,
    specs: ["AMD Ryzen 7 PRO", "8GB DDR4", "256 SSD"],
  },
  {
    id: "lap-001",
    name: "HP 15s-fq5000 Laptop",
    category: "Laptops",
    icon: "💻",
    price: 30000,
    specs: ["Intel Core i3-1215U", "8GB RAM", "256GB SSD", '15.6" FHD Display'],
  },
  {
    id: "lap-002",
    name: "Lenovo IdeaPad 3",
    category: "Laptops",
    icon: "💻",
    price: 24000,
    specs: ["AMD Ryzen 5 5500U", "8GB RAM", "512GB SSD", "Backlit keyboard"],
  },
  {
    id: "lap-003",
    name: "Dell Latitude 3540",
    category: "Laptops",
    icon: "💻",
    price: 20000,
    specs: ["Intel Core i7-1355U", "16GB RAM", "512GB SSD", "Fingerprint reader"],
  },
  {
    id: "epr-001",
    name: "Epson EcoTank L3250",
    category: "Epson Printers",
    icon: "🖨️",
    price: 25500,
    specs: ["Print, scan & copy", "Wi-Fi & USB", "Refillable ink tanks", "Up to 7,500 colour pages"],
  },
  {
    id: "epr-002",
    name: "Epson EcoTank L5290",
    category: "Epson Printers",
    icon: "🖨️",
    price: 42000,
    specs: ["ADF auto document feeder", "Wi-Fi Direct", "Duplex printing", "Borderless photo print"],
  },
  {
    id: "epr-003",
    name: "Epson LQ-350 Dot Matrix",
    category: "Epson Printers",
    icon: "🖨️",
    price: 35800,
    specs: ["24-pin impact printer", "Multi-part forms", "USB & parallel", "Ideal for invoices"],
  },
  {
    id: "lam-001",
    name: "YT-320 A3 Laminator",
    category: "Laminators",
    icon: "📄",
    price: 7000,
    specs: ["A3 & A4 compatible", "Hot & cold lamination", "4-roller system", "Adjustable temperature"],
  },
  {
    id: "lam-002",
    name: "YT-320 A4 Office Laminator",
    category: "Laminators",
    icon: "📄",
    price: 6000,
    specs: ["A4 max width", "3-minute warm-up", "Jam release function", "Metal construction"],
  },
  {
    id: "cctv-001",
    name: "4-Channel DVR CCTV Kit",
    category: "CCTV",
    icon: "📹",
    price: 6500,
    specs: ["4× 1080p bullet cameras", "1TB HDD included", "Night vision 20m", "Mobile app viewing"],
  },
  {
    id: "cctv-002",
    name: "8-Channel NVR IP Kit",
    category: "CCTV",
    icon: "📹",
    price: 8500,
    specs: ["8× 2MP IP cameras", "PoE switch included", "2TB storage", "H.265+ compression"],
  },
  {
    id: "cctv-003",
    name: "Dome Camera 2MP (Single)",
    category: "CCTV",
    icon: "📹",
    price: 1500,
    specs: ["2MP 1080p resolution", "IR night vision", "Weatherproof IP66", "BNC / coax compatible"],
  },
  {
    id: "net-001",
    name: "Cat6 Ethernet Cable 305m Box",
    category: "Networking",
    icon: "🔌",
    price: 5500,
    specs: ["UTP solid copper", "305m pull box", "23 AWG", "Gigabit certified"],
  },
  {
    id: "net-002",
    name: "RJ45 Connector Pack (100pcs)",
    category: "Networking",
    icon: "🔗",
    price: 500,
    specs: ["Cat6 compatible", "Gold-plated contacts", "Crimp type", "100 pieces per pack"],
  },
  {
    id: "net-003",
    name: "Network Patch Panel 24-Port",
    category: "Networking",
    icon: "🔗",
    price: 4500,
    specs: ["Cat6 rated", "19-inch rack mount", "Label strips included", "110 punch-down"],
  },
  {
    id: "cab-001",
    name: "UK 3-Pin Power Cable 1.8m",
    category: "Power Cables",
    icon: "⚡",
    price: 200,
    specs: ["IEC C13 to UK plug", "1.8 metre length", "10A rated", "Desktop & monitor use"],
  },
  {
    id: "cab-002",
    name: "Kettle Lead Power Cable 2m",
    category: "Power Cables",
    icon: "⚡",
    price: 200,
    specs: ["IEC C13 connector", "2 metre cable", "13A fuse", "Heavy-duty copper"],
  },
  {
    id: "adp-001",
    name: "Universal Laptop Adapter 65W",
    category: "Laptop Adapters",
    icon: "🔋",
    price: 2500,
    specs: ["65W output", "8 interchangeable tips", "19V DC output", "Over-voltage protection"],
  },
  {
    id: "adp-002",
    name: "HP Big Pin Adapter",
    category: "Laptop Adapters",
    icon: "🔋",
    price: 1000,
    specs: ["Compatible HP Pavilion", "19.5V 2.31A", "Blue tip connector", "Genuine quality"],
  },
  {
    id: "adp-003",
    name: "Dell Big Pin Adapter",
    category: "Laptop Adapters",
    icon: "🔋",
    price: 1000,
    specs: ["90W power delivery", "Dell 7.4mm barrel tip", "LED indicator", "Short-circuit protection"],
  },
  {
    id: "hdd-001",
    name: "WD 1TB HDD",
    category: "Storage",
    icon: "💾",
    price: 6500,
    specs: ["3.5\" SATA III", "7200 RPM", "64MB cache", "Desktop internal"],
  },
  {
    id: "ssd-001",
    name: " NVME 256GB SSD",
    category: "Storage",
    icon: "💾",
    price: 4500,
    specs: ["M.2 NVMe PCIe 4.0", "256GB capacity", "Up to 3500 MB/s read",],
  },
  {
    id: "ssd-002",
    name: "256GB SATA SSD",
    category: "Storage",
    icon: "💾",
    price: 4500,
    specs: ["2.5\" SATA III", "256GB capacity", "560 MB/s read", "V-NAND technology"],
  },
  {
    id: "enc-001",
    name: "2.5\" USB 3.0 HDD Enclosure",
    category: "Storage",
    icon: "📦",
    price: 1000,
    specs: ["SATA to USB 3.0", "Tool-free design", "LED activity indicator", "UASP supported"],
  },
  {
    id: "enc-002",
    name: "3.5\" USB 3.0 HDD Docking Station",
    category: "Storage",
    icon: "📦",
    price: 1800,
    specs: ["SATA I/II/III", "USB 3.0 & eSATA", "Hot-swap support", "12V power adapter included"],
  },
  {
    id: "ups-001",
    name: "Lightwave LW-650VA UPS",
    category: "UPS",
    icon: "🔋",
    price: 5500,
    specs: ["650VA / 360W", "4× battery-backed outlets", "AVR voltage regulation", "LED status display"],
  },
  {
    id: "ups-002",
    name: "Lightwave LW-1000VA UPS",
    category: "UPS",
    icon: "🔋",
    price: 8500,
    specs: ["1000VA / 600W", "6 outlets", "USB monitoring port", "Surge & spike protection"],
  },
  {
    id: "ups-003",
    name: "Lightwave LW-1500VA Line Interactive",
    category: "UPS",
    icon: "🔋",
    price: 12500,
    specs: ["1500VA / 900W", "Rack/tower convertible", "Replaceable battery", "Ideal for servers"],
  },
  {
    id: "ink-001",
    name: "Epson 003 Black Ink Bottle",
    category: "Epson Inks",
    icon: "🖋️",
    price: 1000,
    specs: ["Original Epson", "EcoTank series", "Up to 4,500 pages", "Smudge-resistant"],
  },
  {
    id: "ink-002",
    name: "Epson 003 Colour Set (4 Bottles)",
    category: "Epson Inks",
    icon: "🖋️",
    price: 4000,
    specs: ["Cyan, Magenta, Yellow, Black", "Original Epson", "EcoTank L3xxx series", "High-yield formula"],
  },
  {
    id: "ink-003",
    name: "Epson 664 Ink Bottle Set",
    category: "Epson Inks",
    icon: "🖋️",
    price: 3500,
    specs: ["4-colour pack", "L-series compatible", "Genuine Epson", "Fade-resistant"],
  },
  {
    id: "rtr-001",
    name: "Tenda F6 Router",
    category: "Routers",
    icon: "📡",
    price: 2000,
    specs: ["Dual-band AC1200", "4× Gigabit LAN ports", "MU-MIMO", "Easy setup app"],
  },
  {
    id: "rtr-002",
    name: "Tenda F3 Wireless N Router",
    category: "Routers",
    icon: "📡",
    price: 1500,
    specs: ["300Mbps wireless N", "2× external antennas", "WISP mode", "Budget home use"],
  },
  {
    id: "rtr-003",
    name: "TP-Link 840 Router",
    category: "Routers",
    icon: "📡",
    price: 5200,
    specs: ["AC1200 dual-band", "4× external antennas", "MU-MIMO", "Guest network"],
  },
  {
    id: "rtr-004",
    name: "TP-Link TL-SG108 8-Port Switch",
    category: "Routers",
    icon: "🔗",
    price: 1500,
    specs: ["8× Gigabit ports", "Plug & play", "Metal casing", "Fanless silent design"],
  },
  {
    id: "rtr-005",
    name: "TP-Link TL-SG105 5-Port Switch",
    category: "Routers",
    icon: "🔗",
    price: 1000,
    specs: ["5× Gigabit ports", "Compact desktop", "Energy efficient", "IEEE 802.3x flow control"],
  },
  {
    id: "ram-001",
    name: "8GB DDR4 3200MHz",
    category: "RAM",
    icon: "🧠",
    price: 3500,
    specs: ["8GB capacity", "DDR4-3200", "CL22 latency", "Desktop DIMM"],
  },
  {
    id: "ram-002",
    name: "16GB DDR4 3200MHz",
    category: "RAM",
    icon: "🧠",
    price: 6500,
    specs: ["16GB single stick", "DDR4-3200", "Lifetime warranty", "Intel & AMD compatible"],
  },
  {
    id: "ram-003",
    name: "8GB DDR5 4800MHz",
    category: "RAM",
    icon: "🧠",
    price: 6500,
    specs: ["8GB DDR5", "4800MHz speed", "Next-gen platforms", "Desktop DIMM"],
  },
 {
    id: "Plotting Machine-001",
    name: "2 feet Redsail Plotter",
    category: "Plotter",
    icon: "🧠",
    price: 42000,
    specs: ["2 Feet", "Artcut & Graphics Disc", "High Speed Cutting", "Cutter"],
  },
  {
    id: "Heatpress Machine-002",
    name: "Freesub Heatpress",
    category: "8-in-ONE Heatrpess",
    icon: "🧠",
    price: 42000,
    specs: ["A3 Size", "Mug & Water Bottle Components", "Cap Press", "Plate Press"],
  },
  {
    id: "cam-001",
    name: "Canon EOS 4000D DSLR Kit",
    category: "Professional Cameras",
    icon: "📷",
    price: 58500,
    specs: ["18MP APS-C sensor", "18-55mm kit lens", "Full HD 1080p video", "Wi-Fi & Canon Camera Connect"],
  },
  {
    id: "cam-002",
    name: "Sony Alpha a6000 Mirrorless",
    category: "Professional Cameras",
    icon: "📷",
    price: 72000,
    specs: ["24.3MP APS-C sensor", "Fast hybrid autofocus", "11 fps burst shooting", "Full HD video recording"],
  },
  {
    id: "cam-003",
    name: "Nikon D3500 DSLR Kit",
    category: "Professional Cameras",
    icon: "📷",
    price: 62000,
    specs: ["24.2MP DX-format sensor", "18-55mm VR kit lens", "Guide mode for beginners", "Bluetooth connectivity"],
  },
  {
    id: "cam-004",
    name: "PTZ Conference Camera 4K",
    category: "Professional Cameras",
    icon: "🎥",
    price: 45000,
    specs: ["4K UHD output", "20× optical zoom", "USB & HDMI connectivity", "Ideal for meetings & streaming"],
  },
  {
    id: "cam-005",
    name: "DSLR Video Camera 4K Pro",
    category: "Professional Cameras",
    icon: "🎬",
    price: 95000,
    specs: ["4K video recording", "External mic input", "Flip touchscreen", "Professional events & vlogging"],
  },
];
